### ISSUE TITLE
Spawned child process inherits process.env.NODE_PATH from Atom

### ISSUE THREAD

**Issue by ldrick** [noseglid/atom-build-npm-apm#24] opened 2017-01-13 14:15 UTC
I got always this error, when I tried to run an npm script within my application.

> npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! {XXX} build-productive: `gulp build-productive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the {XXX} build-productive script 'gulp build-productive'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the {XXX} package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build-productive
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs {XXX}
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls {XXX}
npm ERR! There is likely additional logging output above. 
npm ERR! Please include the following file with any support request:
npm ERR!     /home/{XXX}/npm-debug.log

It took me some time, but I was able to figure out, that on my Ubuntu Machine the child process is spawned with:
`npm run build-productive`
witch calls my local installation of npm (see error).

But the process.env.NODE_PATH from Atom has been provided to the child process and I had to change this line:
```javascript
const env = {FORCE_COLOR: '1', MOCHA_COLORS: '1', NPM_CONFIG_COLOR: 'always', NODE_ENV: ''};
```
to
```javascript
const env = {FORCE_COLOR: '1', MOCHA_COLORS: '1', NPM_CONFIG_COLOR: 'always', NODE_ENV: '', NODE_PATH:'/usr/bin/node'};
```
I would consider it to be better, to be able to specify this within the configuration.

**Comment by noseglid** [comment] 2017-01-13 18:47
This is a duplicate of #18

**Closed as completed by noseglid** 2017-01-13 18:47 UTC

**Comment by ldrick** [comment] 2017-01-16 09:21
Maybe I didn't explain it well, but for me it is not the same, this one results in real Errors, due to spawned child processes searches for files within /opt/atom/resources/app.asar
This is not an directory, and will lead to Errors, telling this is not a directory. For me the process searched for /opt/atom/resources/app.asar/package.json.
#18 is "only" the wrong environment-flag, which I had to solve locally, too.

Somehow, I do not really know why, my Windows-Users do not have the problem mentioned here.
