### ISSUE TITLE
editor windows hangs on show targets

### ISSUE THREAD

**Issue by black-snow** [noseglid/atom-build-npm-apm#21] opened 2016-07-20 13:35 UTC
OS: Mac OS X 10.11.5 (15F34)
Version: 0.12.0
Atom Version: 1.8.0

Recently either this package or the build package (idk) hangs up my editor window. When I hit `cmd+alt+t` to display the targets the editor hangs. After a while a dialog pops up telling my that the editor window does not respond. Clicking 'wait' does not help. Tested it five time - same result everytime.

Maybe build-npm has a problem with my project structure. For this project it looks like this:
project root contains `.git` directory (and other git stuff) and a subdirectory. That subdirectory contains the project-level `package.json`.

**Comment by noseglid** [comment] 2016-07-22 18:22
Dupe of https://github.com/noseglid/atom-build/issues/447

**Closed as completed by noseglid** 2016-07-22 18:22 UTC
